### ISSUE TITLE
Error running 23_recog.sh on pre-trained dataset

### ISSUE THREAD

**Issue by aaronrr** [rwth-i6/returnn-experiments#9]
I am trying to test out running the pretrained model on my system. I have downloaded the model from http://www-i6.informatik.rwth-aachen.de/~zeyer/models/librispeech/enc-dec/2018.zeyer.exp3.ctc/ and renamed the file `network.238.data-00000-of-00001` to `train-scores.data` and put it in /data/exp-returnn, as well as moved and renamed the `exp3.ctc.config` to `/returnn.config`.

Upon running ./23_recog.sh I get the output:

`
# You can run this already while it is still training.
# Run it a final time when the training is finished.

experiment=returnn-pretrained
+ experiment=returnn-pretrained
test -e data/exp-$experiment  # experiment existing?
+ test -e data/exp-returnn-pretrained
test -e data/exp-$experiment/train-scores.data  # some epochs trained?
+ test -e data/exp-returnn-pretrained/train-scores.data

# Get us some recommended epochs to do recog on.
epochs=$(./tools/recommend-recog-epochs.py --experiment $experiment)
./tools/recommend-recog-epochs.py --experiment $experiment
++ ./tools/recommend-recog-epochs.py --experiment returnn-pretrained
Experiment config: returnn-pretrained.config
EXCEPTION
Traceback (most recent call last):
  File "./tools/recommend-recog-epochs.py", line 46, in <module>
    line: train_scores_data = open(train_scores_fn).read()
    locals:
      train_scores_data = <not found>
      open = <builtin> <built-in function open>
      train_scores_fn = <local> 'data/exp-returnn-pretrained/train-scores.data', len = 45
      read = <not found>
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    line: return codecs.ascii_decode(input, self.errors)[0]
    locals:
      codecs = <global> <module 'codecs' from '/usr/lib/python3.5/codecs.py'>
      codecs.ascii_decode = <global> <built-in function ascii_decode>
      input = <local> b'{\xba[\xbegQ\x0f\xbf\x0b\xd4\xc0\xbe\x00\xe3:\xbe\xdbm\xfd\xbeaT\x1d\xbf\r\x14\x80>\xa4\xde\xe7\xbd\x0f\xd1\xff=\xd0\r\x86<X3\x03\xbfnv\xd7\xbe\xe7b\x89>\x05:\x86\xbe\x07G\xc7>\xda\xf6\x9d\xbe\x93\xf4\x85\xbe\xbe\x93\x8b\xbe\xfb\xeb\x06>\x9e\xe7\xa3>\xa8\x93\\=\x97O\xb5=\xfc\xd3\x96\xbe\x8e\xe3..., len = 751448632
      self = <local> <encodings.ascii.IncrementalDecoder object at 0x7f761d520ac8>
      self.errors = <local> 'strict', len = 6
UnicodeDecodeError: 'ascii' codec can't decode byte 0xba in position 1: ordinal not in range(128)
+ epochs=`

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xba in position 1: ordinal not in range(128)` seems to be a problem loading data from the train-scores.data file is there something wrong in my workflow?

**Comment by albertz** [comment]
`23_recog.sh` uses `tools/recommend-recog-epochs.py` to get epochs to do recognition on. That script uses the training/cv scores, which are saved by Returnn in the `learning_rate_file`.
See in `returnn.config`: `learning_rate_file = "data/exp-%s/train-scores.data" % setup_name`.
(In other example configs, you often see `learning_rate_file = "newbob.data"`.)
You do not have that file `train-scores.data`. You incorrectly renamed the model data file to that name.

A simple workaround for now: In `23_recog.sh`, replace this line:

    epochs=$(./tools/recommend-recog-epochs.py --experiment $experiment)

By:

    epochs=238

**Comment by aaronrr** [comment]
Yes, this has resolved it. Thanks for the help!
